### ISSUE TITLE
서울 시티투어 버스 코스 정보 확인하기

### ISSUE THREAD

**Issue by opklnm102** [Mash-Up-MapC/MapC-backend#20]
# 서울 시티투어 버스 코스 정보 확인하기

## User Story
* 서울 시티투어 버스를 이용하고 싶은 관광객으로써
* 코스 정보를 보고 싶다
* 어떤 코스가 있는지 확인 후 예약하고 싶기 때문에

<br>

## UAC
* 코스 리스트를 볼 수 있다 #24
* 코스별 상세 정보를 볼 수 있다 #25
  * 코스 이름
  * 코스의 관광지 사진
  * 예매 가격
  * 운행 시간
  * 코스 설명
  * 주요 관광지
  * 코스 지도(루트)
  * 코스의 명소 정보
* 코스별 상세 정보 화면의 지도에서 루트를 볼 수 있다 #30

<br>

> #### Reference
> * [Zeplin의 Main 1-1, 1-2 디자인 참고](https://app.zeplin.io/project/5b6bab573b0600688b8ec7d4/dashboard)

---

<br>

## Check List
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 issue 내용만 확인하고도 모르는 사람도 파악할 수 있을 정도로 기술되었는가? (무엇을, 언제, 어디서...)
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 Label을 추가했는가?
- [x] Assginees를 추가했는가?
- [ ] Estimate를 추가했는가?
- [x] 관련 Milestone이 있다면 추가했는가?
- [ ] 관련 Epics가 있다면 추가했는가?
