### ISSUE TITLE
서울 시티투어 버스 코스 예약하기

### ISSUE THREAD

**Issue by opklnm102** [Mash-Up-MapC/MapC-backend#21]
# 서울 시티투어 버스 코스 예약하기

## User Story
* 서울 시티투어 버스를 이용하고 싶은 관광객으로써
* 특정 코스의 버스를 예약하고 싶다
* 시티투어 버스를 타고 관광하기 위해서

<br>

## UAC
* 예약을 위한 코스 리스트를 볼 수 있다 #26
* 예매를 할 수 있다 #27
  * 인원 - 성인/학생
  * 날짜
  * 시간
  * 예약자 이름
  * 예약자 연락처
  * 결제 금액
  * 할인 안내
  * 환불 정책
* 예매 완료 결과를 볼 수 있다 #27

<br>

> #### Reference
> * [Zeplin의 예약 디자인 참고](https://app.zeplin.io/project/5b6bab573b0600688b8ec7d4/dashboard)

---

<br>

## Check List
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 issue 내용만 확인하고도 모르는 사람도 파악할 수 있을 정도로 기술되었는가? (무엇을, 언제, 어디서...)
- [x] reference가 있다면 추가했는가?
- [ ] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 Label을 추가했는가?
- [x] Assginees를 추가했는가?
- [ ] Estimate를 추가했는가?
- [x] 관련 Milestone이 있다면 추가했는가?
- [ ] 관련 Epics가 있다면 추가했는가?
