### ISSUE TITLE
관광지 정보 오디오 가이드

### ISSUE THREAD

**Issue by opklnm102** [Mash-Up-MapC/MapC-backend#22]
# 관광지 정보 오디오 가이드

## User Story
* 서울 시티투어 버스를 이용하는 관광객으로써
* 근처 관광지의 정보를 음성으로 듣고 싶다
* 흔들리는 버스에서 글보다는 음성이 더 편하기 때문에

<br>

## UAC
* 현재 지나고 있는 관광지에 대한 정보를 볼 수 있다 # 

<br>

> #### Reference
> * 현재 디자인 없으므로 추후 업데이트 예정

---

<br>

## Check List
- [x] issue 제목은 유의미한가?
- [ ] issue 내용은 issue 내용만 확인하고도 모르는 사람도 파악할 수 있을 정도로 기술되었는가? (무엇을, 언제, 어디서...)
- [x] reference가 있다면 추가했는가?
- [ ] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 Label을 추가했는가?
- [x] Assginees를 추가했는가?
- [ ] Estimate를 추가했는가?
- [x] 관련 Milestone이 있다면 추가했는가?
- [ ] 관련 Epics가 있다면 추가했는가?

**Comment by opklnm102** [comment]
해당 story는 디자인보고 나서 다시 디벨롭해야할듯 해요

**Comment by KiWooyoung** [comment]
동희 합니당.
