### ISSUE TITLE
코스별 버스 운행정보 확인

### ISSUE THREAD

**Issue by opklnm102** [Mash-Up-MapC/MapC-backend#23]
# 코스별 버스 운행정보 확인

## User Story
* 서울 시티투어 버스를 이용하는 관광객으로써
* 코스별 버스 운행정보를 실시간으로 확인하고 싶다
* 버스에 탑승하고 싶기 때문에

<br>

## UAC
* 코스별 노선 정보를 볼 수 있다 #28
  * 기점 ~ 종점
  * 배차 간격
  * 정류장 이름
* 운행중인 버스의 위치를 실시간으로 확인할 수 있다 #29 
  * 정류장 사이의 위치
  * 도착 예정 시간

<br>

> #### Reference
> * [Zeplin의 Main4 Route 디자인 참고](https://app.zeplin.io/project/5b6bab573b0600688b8ec7d4/dashboard)

---

<br>

## Check List
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 issue 내용만 확인하고도 모르는 사람도 파악할 수 있을 정도로 기술되었는가? (무엇을, 언제, 어디서...)
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 Label을 추가했는가?
- [x] Assginees를 추가했는가?
- [ ] Estimate를 추가했는가?
- [x] 관련 Milestone이 있다면 추가했는가?
- [ ] 관련 Epics가 있다면 추가했는가?
