### ISSUE TITLE
Entity Modeling하기

### ISSUE THREAD

**Issue by opklnm102** [Mash-Up-MapC/MapC-backend#33]
# Entity Modeling하기
* 기획/디자인을 참고하여 DB Table 및 JPA Entity Modeling을 한다

<br> 

## relate to issue
* DB Table 모델링(#11)
* JPA Entity Modeling하기(#34)

> #### Reference
> * [Zeplin의 디자인 참고](https://app.zeplin.io/project/5b6bab573b0600688b8ec7d4/dashboard)

---

<br>

## Check List
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 issue 내용만 확인하고도 모르는 사람도 파악할 수 있을 정도로 기술되었는가? (무엇을, 언제, 어디서...)
- [x] reference가 있다면 추가했는가?
- [x] 관련 issue가 있다면 추가했는가?
- [x] 유의미한 Label을 추가했는가?
- [x] Assginees를 추가했는가?
- [ ] Estimate를 추가했는가?
- [x] 관련 Milestone이 있다면 추가했는가?
- [ ] 관련 Epics가 있다면 추가했는가?

**Comment by opklnm102** [comment]
하위 task들이 모두 done되었으므로 close할께요
