### ISSUE TITLE
Backend architecture 구성하기

### ISSUE THREAD

**Issue by opklnm102** [Mash-Up-MapC/MapC-backend#39]
# Backend architecture 구성하기
* Backend system에 대한 architecture를 구성한다
  * AWS infra architecture
  * CI/CD pipeline
  * application architecture

<br> 

## relate to issue
* AWS 계정 & 인프라 셋팅하기(#37)
* CI/CD 구축(#38)
* Backend architecture 문서화하기(#40)

<br>

> #### Reference
> * [AWS 아키텍처 센터](https://aws.amazon.com/ko/architecture)
> * [자동 확장 가능한 콘서트 티켓 예매 사이트 구축하기 - 아마존 웹 서비스를 다루는 기술](http://pyrasis.com/book/TheArtOfAmazonWebServices/Chapter32)
> * [글로벌 사진 사이트 구축하기 - 아마존 웹 서비스를 다루는 기술](http://pyrasis.com/book/TheArtOfAmazonWebServices/Chapter31)
> * [AWS 백서](https://aws.amazon.com/ko/whitepapers)

<br>

## Check List
- [x] issue 제목은 유의미한가?
- [x] issue 내용은 issue 내용만 확인하고도 모르는 사람도 파악할 수 있을 정도로 기술되었는가? (무엇을, 언제, 어디서...)
- [ ] reference가 있다면 추가했는가?
- [ ] 관련 issue가 있다면 추가했는가?
- [ ] 유의미한 Label을 추가했는가?
- [ ] Assginees를 추가했는가?
- [ ] Estimate를 추가했는가?
- [ ] 관련 Milestone이 있다면 추가했는가?
- [ ] 관련 Epics가 있다면 추가했는가?

**Comment by KiWooyoung** [comment]
아키텍처 같이 생각해봐도 될까요~?!!

**Comment by opklnm102** [comment]
그럼여 당연히 같이 해야죠
